### ISSUE TITLE
Drop graceful-fs?

### ISSUE THREAD

**Issue by phated** [gulpjs/fs-mkdirp-stream#8]
We've had so many issues with graceful-fs, I'm wondering if we should just stop using it.

@contra @coreyfarrell What do you think?

**Comment by coreyfarrell** [comment]
Looking at the usage of `fs` from this module with changes made by graceful-fs:
* `fs.mkdir`: not patched by graceful-fs
* `fs.stat`: patched by graceful-fs but only to deal with negative `uid` / `gid` in unspecified very old versions of node.  This module does not read `uid` or `gid` so not important here.
* `fs.chmod`: always suppress `ENOSYS`. suppress `EINVAL` and `EPERM` errors when not running under root.

For this module I think `fs.chmod` error handling is the only thing which matters.  I just checked `npm ls graceful-fs` for this module and nothing performs `require('graceful-fs').gracefulify(require('fs'))` so we wouldn't be unintentionally using the patched `chmod` from graceful-fs.

**Comment by phated** [comment]
Hmmm, I think the `chmod` stuff might actually matter for Windows devs using gulp. @coreyfarrell do you think that those suppressions are worth keeping it in?

**Comment by coreyfarrell** [comment]
Windows doesn't support chmod so I think we need to suppress ENOSYS at minimum.

**Comment by phated** [comment]
Makes sense. Let's keep graceful-fs in all the gulp modules.
